version: '3.7'
services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=${PGDATABASE}
            - POSTGRES_USER=${PGUSER}
            - POSTGRES_PASSWORD=${PGPASSWORD}
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '${PGPORT}:5432'
